---
#given name of wf which will be displayed on gh repo
name: demo_01
on:
  #run the wf when user push the local commits to given branch in rr
  push:
    #we can given filters on each event like for which branch event will occur
    branches:
      - main
  #run the wf when pull_request event occurs
  pull_request:
    branches: ["main", "feature/1"]
  #allow users to manually trigger and run the wf
  workflow_dispatch:
jobs:
  #give job name
  job_01:
    #machine type where job will run. machine can be gh-hosted or self-hosted runner
    runs-on: ubuntu-latest
    #step refers to seq of tasks to be executed when we run job inside the given runner
    steps:
      #name of the step
      - name: task_01 -> run single line shell cmd
        #run shell cmds
        # > means will not preserve no of lines so cmd will run in single line
        run: >
          echo hello japan-1
          osaka-2
      - name: task_02 -> run multi-line shell cmds
        # | means will preserve no of lines so cmd will run as it is and not in single line
        run: |
          echo hi-1
          echo mum-1
          mkdir dir1 && cd dir1 && touch a1 && echo mum-3>a1
      #give custom action that will perform specific task
      - uses: actions/checkout@v4
